CREATE TABLE [TABELA DE VENDEDORES]
([MATRICULA] [VARCHAR] (5) NOT NULL, 
[NOME] [VARCHAR] (100) NULL, 
[CIDADE] [VARCHAR] (100) NULL,
[PERCENTUAL COMISSÃO] [FLOAT] NOT NULL,
[DATA INICIO] [DATE] NOT NULL,
[TEM DEPENDENTE] [BIT])

ALTER TABLE [TABELA DE VENDEDORES] ADD CONSTRAINT PK_MARICULA
PRIMARY KEY CLUSTERED ([MATRICULA])

INSERT INTO [TABELA DE VENDEDORES]
([NOME], 
[MATRICULA],
[CIDADE],
[PERCENTUAL COMISSÃO],
[DATA INICIO],
[TEM DEPENDENTE]
)

VALUES ('Alberto de Sá Verneck','00239','São Paulo', 0.08,'2020-06-05',1)