INSERT INTO [TABELA DE VENDEDORES]
([NOME], 
[MATRICULA],
[CIDADE],
[PERCENTUAL COMISSÃO],
[DATA INICIO],
[TEM DEPENDENTE]
)

VALUES ('Marcela Almeida', '00240', 'Rio de Janeiro', 0.007, '12-01-2021', 'FALSE')